SET datestyle to DMY;
insert into genres(name) values ('Acción'),
                                ('Aventura'),
                                ('Casual'),
                                ('Rol'),
                                ('Simulación'),
                                ('Estrategia'),
                                ('Rogue-like'),
                                ('Disparos'),
                                ('Novela Visual'),
                                ('Terror'),
                                ('Música'),
                                ('Puzzles'),
                                ('Lucha'),
                                ('Carreras'),
                                ('Plataformas'),
                                ('City Building'),
                                ('Tower Defense'),
                                ('Sandbox'),
                                ('Deportes'),
                                ('MOBA'),
                                ('MMO'),
                                ('Arcade'),
                                ('Supervivencia'),
                                ('Realidad Virtual'),
                                ('Gestión'),
                                ('Educativos'),
                                ('Cartas/Juegos de Mesa'),
                                ('Sigilo'),
                                ('Clicker'),
                                ('JRPG'),
                                ('Souls-like'),
                                ('Idle');

insert into games(name,description,developer,publisher,imageurl,publishdate) values
('DOTA 2','Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it''s their 10th hour of play or 1,000th, there''s always something new to discover. With regular updates that ensure a constant evolution of gameplay, features, and heroes, Dota 2 has taken on a life of its own.',
 'Valve','Valve','https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg?t=1680910438',
 '09/04/2013'),
('Path of Exile','You are an Exile, struggling to survive on the dark continent of Wraeclast, as you fight to earn power that will allow you to exact your revenge against those who wronged you. Created by hardcore gamers, Path of Exile is an online Action RPG set in a dark fantasy world.',
     'Grinding Gear Games','Grinding Gear Games','https://cdn.cloudflare.steamstatic.com/steam/apps/238960/header.jpg?t=1681023011',
 '23/10/2013'),
('Destiny 2','Destiny 2 is an action MMO with a single evolving world that you and your friends can join anytime, anywhere, absolutely free.',
 'Bungie','Bungie','https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg?t=1681043686',
 '01/10/2019'),
('Rust','The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife and other inhabitants, the environment, other survivors. Do whatever it takes to last another night.',
 'Facepunch Studios', 'Facepunch Studios','https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg?t=1681142239',
 '08/02/2018'),
('Team Fortress 2','Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!',
 'Valve','Valve','https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg?t=1681164012',
 '10/10/2007'),
('Lost Ark','Embark on an odyssey for the Lost Ark in a vast, vibrant world: explore new lands, seek out lost treasures, and test yourself in thrilling action combat in this action-packed free-to-play RPG.',
 'Smilegate RPG','Amazon Games','https://cdn.cloudflare.steamstatic.com/steam/apps/1599340/header.jpg?t=1680074149',
 '11/02/2022'),
('Call of Duty®: Modern Warfare® II | Warzone™ 2.0','Call of Duty®: Modern Warfare® II drops players into an unprecedented global conflict that features the return of the iconic Operators of Task Force 141.',
 'Infinity Ward','Activision','https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/header.jpg?t=1681115690',
 '28/10/2022'),
('PUBG: BATTLEGROUNDS','Play PUBG: BATTLEGROUNDS for free. Land on strategic locations, loot weapons and supplies, and survive to become the last team standing across various, diverse Battlegrounds. Squad up and join the Battlegrounds for the original Battle Royale experience that only PUBG: BATTLEGROUNDS can offer.',
 'KRAFTON, Inc.','KRAFTON, Inc.','https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg?t=1681111174',
 '21/12/2017'),
('Unturned','You''re a survivor in the zombie infested ruins of society, and must work with your friends and forge alliances to remain among the living.',
 'Smartly Dressed Games','Smartly Dressed Games','https://cdn.cloudflare.steamstatic.com/steam/apps/304930/header.jpg?t=1680553059',
 '07/07/2017'),
('War Thunder','War Thunder is the most comprehensive free-to-play, cross-platform, MMO military game dedicated to aviation, armoured vehicles, and naval craft, from the early 20th century to the most advanced modern combat units. Join now and take part in major battles on land, in the air, and at sea.',
 'Gaijin Entertainment','Gaijin Distribution KFT','https://cdn.cloudflare.steamstatic.com/steam/apps/236390/header.jpg?t=1681113564',
 '15/08/2013'),
('No Man''s Sky','No Man''s Sky is a game about exploration and survival in an infinite procedurally generated universe.',
 'Hello Games','Hello Games','https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg?t=1680861709',
 '12/08/2018'),
('Grand Theft Auto V','Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.',
 'Rockstar North','Rockstar Games','https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg?t=1681148065',
 '13/04/2015'),
('Slay the Spire','We fused card games and roguelikes together to make the best single player deckbuilder we could. Craft a unique deck, encounter bizarre creatures, discover relics of immense power, and Slay the Spire!',
 'Mega Crit Games','Mega Crit Games','https://cdn.cloudflare.steamstatic.com/steam/apps/646570/header.jpg?t=1678835945',
 '23/01/2019'),
('Subnautica','Descend into the depths of an alien underwater world filled with wonder and peril. Craft equipment, pilot submarines and out-smart wildlife to explore lush coral reefs, volcanoes, cave systems, and more - all while trying to survive.',
 'Unknown Worlds Entertainment','Unknown Worlds Entertainment','https://cdn.cloudflare.steamstatic.com/steam/apps/264710/header.jpg?t=1681051674',
 '24/01/2018'),
('CLANNAD','From the world renowned visual novel studio Key, the highly rated story of CLANNAD is now available on Steam! Improved visuals, achievement integration, and Dangopedia make this the best version of CLANNAD to date.',
 'VisualArts/Key','Sekai Project','https://cdn.cloudflare.steamstatic.com/steam/apps/324160/header.jpg?t=1679267291',
 '23/11/2015'),
('Euro Truck Simulator 2','Travel across Europe as king of the road, a trucker who delivers important cargo across impressive distances! With dozens of cities to explore, your endurance, skill and speed will all be pushed to their limits.',
 'SCS Software','SCS Software','https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg?t=1680784755',
 '18/11/2012'),
('Dead Cells','Dead Cells is a rogue-lite, metroidvania inspired, action-platformer. You''ll explore a sprawling, ever-changing castle... assuming you’re able to fight your way past its keepers in 2D souls-lite combat. No checkpoints. Kill, die, learn, repeat. Regular free content updates!',
 'Motion Twin','Motion Twin','https://cdn.cloudflare.steamstatic.com/steam/apps/588650/header.jpg?t=1681029280',
 '06/08/2018'),
('Subnautica: Below Zero','Dive into a freezing underwater adventure on an alien planet. Below Zero is set two years after the original Subnautica. Return to Planet 4546B to uncover the truth behind a deadly cover-up. Survive by building habitats, crafting tools, & diving deeper into the world of Subnautica.',
 'Unknown Worlds Entertainment','Unknown Worlds Entertainment','https://cdn.cloudflare.steamstatic.com/steam/apps/848450/header.jpg?t=1681139278',
 '14/05/2021'),
('PowerWash Simulator','Release the Pressure with PowerWash Simulator! Wash away your worries with the soothing sounds of high-pressure water. Fire up your power washer and blast away every speck of dirt and grime you can find, all with the simple satisfaction of power-washing to a sparkling finish.',
 'FuturLab','Square Enix','https://cdn.cloudflare.steamstatic.com/steam/apps/1290000/header.jpg?t=1680766484',
 '14/07/2022'),
('Lawn Mowing Simulator','Experience the beauty and detail of mowing the Great British countryside in Lawn Mowing Simulator, the only simulator that allows you to ride an authentic and expansive roster of real-world licensed lawn mowers from prestigious manufacturers; Toro, SCAG and STIGA as you manage your business.',
 'Skyhook Games','Curve Games','https://cdn.cloudflare.steamstatic.com/steam/apps/1480560/header.jpg?t=1678835755',
 '10/08/2021'),
('Deep Rock Galactic','Deep Rock Galactic is a 1-4 player co-op FPS featuring badass space Dwarves, 100% destructible environments, procedurally-generated caves, and endless hordes of alien monsters.',
 'Ghost Ship Games','Coffee Stain Publishing','https://cdn.cloudflare.steamstatic.com/steam/apps/548430/header.jpg?t=1680715136',
 '13/05/2020'),
('Bloons TD 6','The Bloons are back and better than ever! Get ready for a massive 3D tower defense game designed to give you hours and hours of the best strategy gaming available.',
 'Ninja Kiwi','Ninja Kiwi','https://cdn.cloudflare.steamstatic.com/steam/apps/960090/header.jpg?t=1681168213',
 '18/12/2018'),
('Apex Legends','Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.',
'Respawn Entertainment','Electronic Arts','https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg?t=1681146027',
 '5/11/2020'),
('Counter-Strike: Global Offensive','Counter-Strike: Global Offensive (CS: GO) expands upon the team-based action gameplay that it pioneered when it was launched 19 years ago. CS: GO features new maps, characters, weapons, and game modes, and delivers updated versions of the classic CS content (de_dust2, etc.).',
 'Valve','Valve','https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg?t=1680295115',
 '21/08/2012');